version: "3"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    volumes: 
        - ~/go/src/iwantjob/mongo:/data/db
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0",  "--dbpath", "/data/db"]
  # mongo1:
  #   hostname: mongo1
  #   container_name: mongo1
  #   image: mongo
  #   # volumes: 
  #   #     - ~/go/src/iwantjob/mongo:/data/db
  #   ports:
  #     - 27018:27017
  #   restart: always
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  # mongo2:
  #   hostname: mongo2
  #   container_name: mongo2
  #   image: mongo
  #   # volumes: 
  #   #     - ~/go/src/iwantjob/mongo:/data/db
  #   ports:
  #     - 27019:27017
  #   restart: always
  #   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

