// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: proto/iwantjob.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ImageResp) Reset() {
	*x = ImageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iwantjob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResp) ProtoMessage() {}

func (x *ImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iwantjob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResp.ProtoReflect.Descriptor instead.
func (*ImageResp) Descriptor() ([]byte, []int) {
	return file_proto_iwantjob_proto_rawDescGZIP(), []int{0}
}

func (x *ImageResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  int32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iwantjob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iwantjob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_proto_iwantjob_proto_rawDescGZIP(), []int{1}
}

func (x *GetListReq) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *GetListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Samples []*Cube `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iwantjob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iwantjob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_proto_iwantjob_proto_rawDescGZIP(), []int{2}
}

func (x *List) GetSamples() []*Cube {
	if x != nil {
		return x.Samples
	}
	return nil
}

type Cube struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid    string `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Url    string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Id     string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Cube) Reset() {
	*x = Cube{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iwantjob_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cube) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cube) ProtoMessage() {}

func (x *Cube) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iwantjob_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cube.ProtoReflect.Descriptor instead.
func (*Cube) Descriptor() ([]byte, []int) {
	return file_proto_iwantjob_proto_rawDescGZIP(), []int{3}
}

func (x *Cube) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *Cube) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Cube) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Cube) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Cube) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Cube) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateCubeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid    string `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Url    string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *CreateCubeReq) Reset() {
	*x = CreateCubeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iwantjob_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCubeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCubeReq) ProtoMessage() {}

func (x *CreateCubeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iwantjob_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCubeReq.ProtoReflect.Descriptor instead.
func (*CreateCubeReq) Descriptor() ([]byte, []int) {
	return file_proto_iwantjob_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCubeReq) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *CreateCubeReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateCubeReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateCubeReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCubeReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type UploadImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid   string `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *UploadImageReq) Reset() {
	*x = UploadImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_iwantjob_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq) ProtoMessage() {}

func (x *UploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iwantjob_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq.ProtoReflect.Descriptor instead.
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return file_proto_iwantjob_proto_rawDescGZIP(), []int{5}
}

func (x *UploadImageReq) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *UploadImageReq) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_proto_iwantjob_proto protoreflect.FileDescriptor

var file_proto_iwantjob_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x77, 0x61, 0x6e, 0x74, 0x6a, 0x6f, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x1d, 0x0a,
	0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3a, 0x0a, 0x0a,
	0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x75, 0x62, 0x65, 0x52, 0x07,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x04, 0x43, 0x75, 0x62, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x71, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x62, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x66, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x22, 0x38, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x9e,
	0x01, 0x0a, 0x02, 0x44, 0x62, 0x12, 0x2b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x00, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x62, 0x65,
	0x12, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x75, 0x62, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43,
	0x75, 0x62, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42,
	0x0e, 0x5a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_iwantjob_proto_rawDescOnce sync.Once
	file_proto_iwantjob_proto_rawDescData = file_proto_iwantjob_proto_rawDesc
)

func file_proto_iwantjob_proto_rawDescGZIP() []byte {
	file_proto_iwantjob_proto_rawDescOnce.Do(func() {
		file_proto_iwantjob_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_iwantjob_proto_rawDescData)
	})
	return file_proto_iwantjob_proto_rawDescData
}

var file_proto_iwantjob_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_iwantjob_proto_goTypes = []interface{}{
	(*ImageResp)(nil),      // 0: model.ImageResp
	(*GetListReq)(nil),     // 1: model.getListReq
	(*List)(nil),           // 2: model.List
	(*Cube)(nil),           // 3: model.Cube
	(*CreateCubeReq)(nil),  // 4: model.createCubeReq
	(*UploadImageReq)(nil), // 5: model.UploadImageReq
}
var file_proto_iwantjob_proto_depIdxs = []int32{
	3, // 0: model.List.samples:type_name -> model.Cube
	1, // 1: model.Db.GetList:input_type -> model.getListReq
	4, // 2: model.Db.CreateCube:input_type -> model.createCubeReq
	5, // 3: model.Db.UploadImage:input_type -> model.UploadImageReq
	2, // 4: model.Db.GetList:output_type -> model.List
	3, // 5: model.Db.CreateCube:output_type -> model.Cube
	0, // 6: model.Db.UploadImage:output_type -> model.ImageResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_iwantjob_proto_init() }
func file_proto_iwantjob_proto_init() {
	if File_proto_iwantjob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_iwantjob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iwantjob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iwantjob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iwantjob_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cube); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iwantjob_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCubeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_iwantjob_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_iwantjob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iwantjob_proto_goTypes,
		DependencyIndexes: file_proto_iwantjob_proto_depIdxs,
		MessageInfos:      file_proto_iwantjob_proto_msgTypes,
	}.Build()
	File_proto_iwantjob_proto = out.File
	file_proto_iwantjob_proto_rawDesc = nil
	file_proto_iwantjob_proto_goTypes = nil
	file_proto_iwantjob_proto_depIdxs = nil
}
