version: '3.4'
services:
  app:
    expose:
        - "8080"
    ports:
        - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - 'mongo'
  mongo:
      image: 'mongo:latest'
      container_name: 'mongo'
      ports:
        - '27100:27017'
